# SPDX-FileCopyrightText: 2026 Kalle Fagerberg
#
# SPDX-License-Identifier: CC0-1.0

name: release
on:
  push:
    tags:
      - "v*"

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      # Required to upload binaries to GitHub releases
      contents: write
      # Required for signing (sigstore)
      attestations: write
      # Required for using GitHub IdP (when signing)
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: setup go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # 7.0.0
        with:
          go-version-file: go.mod
          cache: false # no cache to avoid cache-poisoning: https://docs.zizmor.sh/audits/#cache-poisoning

      - uses: jdx/mise-action@7e36c90d9ab29c415a2384db3006f3ec8a8cc654 # v4.2.4
        with:
          cache: false # no cache to avoid cache-poisoning: https://docs.zizmor.sh/audits/#cache-poisoning

      - name: create package
        run: |
          mise run package

      - name: attest release artifacts
        uses: actions/attest-build-provenance@4d101475d8b20a2381f78447822ac1eab6504dd8 # v4.2.2
        with:
          subject-path: "dist/*.zip"

      - name: upload assets to release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload "$GITHUB_REF_NAME" -- dist/*.zip
