# SPDX-FileCopyrightText: 2026 Kalle Fagerberg
#
# SPDX-License-Identifier: CC0-1.0

name: release
on:
  push:
    tags:
      - "v*"

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      # Required to upload binaries to GitHub releases
      contents: write
      # Required for signing (sigstore)
      attestations: write
      # Required for using GitHub IdP (when signing)
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: setup go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # 6.3.0
        with:
          go-version-file: go.mod
          cache: false # no cache to avoid cache-poisoning: https://docs.zizmor.sh/audits/#cache-poisoning

      - uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
        with:
          cache: false # no cache to avoid cache-poisoning: https://docs.zizmor.sh/audits/#cache-poisoning

      - name: create package
        run: |
          mise run package

      - name: attest release artifacts
        uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4.1.0
        with:
          subject-path: "dist/*.zip"

      - name: upload assets to release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload "$GITHUB_REF_NAME" -- dist/*.zip
